from .algorithm_wrapper import AlgorithmWrapper
from .her_wrapper import HERAlgorithmWrapper, latent_based_goal_predicated_reward_fn
from .her_wrapper2 import HERAlgorithmWrapper2, latent_based_goal_predicated_reward_fn2

from .ther_wrapper import THERAlgorithmWrapper, predictor_based_goal_predicated_reward_fn