from .algorithm_wrapper import AlgorithmWrapper
from .her_wrapper import HERAlgorithmWrapper, latent_based_goal_predicated_reward_fn
from .her_wrapper2 import HERAlgorithmWrapper2, latent_based_goal_predicated_reward_fn2

from .ther_wrapper import THERAlgorithmWrapper, predictor_based_goal_predicated_reward_fn
from .ther_wrapper2 import THERAlgorithmWrapper2, predictor_based_goal_predicated_reward_fn2
from .ther_wrapper2 import batched_predictor_based_goal_predicated_reward_fn2

from .ether_wrapper import ETHERAlgorithmWrapper
from .ela_wrapper import ELAAlgorithmWrapper

from .reward_prediction_wrapper import RewardPredictionAlgorithmWrapper
